### ISSUE TITLE
Improve readability of meta language

### ISSUE THREAD

**Issue by bvssvni** [PistonDevelopers/meta#262]
Some ideas for improvement:
- [x] All reserved rules should start with `.`
- [x] All assignments to properties should use `:`
- [x] String references should start with `_`
- [x] The "separated_by" rule could take two arguments `(by_rule rule)` instead of `(by_rule){rule}`
- [x] Add support for simple single line (`//`) and multiple line comments (`/* .. */`)
- [x] Use `name` instead of `"name"` in the rule names, disallow spaces
- [x] `name:"alias"` instead of `@"name""alias"`
- [x] Prevent node and node references from starting with `_`
- [x] Prevent node and node references from starting with `.`
- [x] `"token":"property"` instead of `"token""property"`
- [x] Use `=` for assigning a rule to a node

**Comment by bvssvni** [comment]
One problem is the ambiguity between a string alias and a rule.
