### ISSUE TITLE
Replace old meta syntax with the new one

### ISSUE THREAD

**Issue by bvssvni** [PistonDevelopers/meta#264]
This can be done gradually without breaking existing code.
### Step 1
- [x] Add `syntax2` that bootstraps to the new syntax
- [x] Bump to 0.15.0
### Step 2

Will break because `bootstrap::rules` returns new built-in rules.
- [x] Describe the old syntax in the new syntax
- [x] Replace the internal rules with the improved syntax
- [x] Bootstrap the old syntax in the new syntax
- [x] Bump to 0.17.0
### Step 3

This will break, but it will be possible to still use the old syntax through bootstrapping.
- [x] Update README with new rules
- [x] Remove `syntax`
- [x] Rename `syntax2` to `syntax`
- [x] Bump to 0.22.0
