### ISSUE TITLE
Add struct `Convert` for converting meta data

### ISSUE THREAD

**Issue by bvssvni** [PistonDevelopers/meta#299]
Currently there are a bunch of methods taking `&[Range<MetaData>], offset: usize`. This could be put in a struct `Convert` to encapsulate the state. Could use same pattern as in the read_token library.

``` Rust
pub struct Convert<'a> {
    data: &'a [Range<MetaData>],
    offset: usize,
}
```

Move functions to methods on `Convert`:
- [x] update
- [x] start_node
- [x] end_node
- [x] ignore
- [x] meta_string
- [x] meta_f64
- [x] meta_bool

Use `Convert` internally in `convert`:
- [x] read_string
- [x] read_sequence
- [x] read_set
- [x] read_until_any_or_whitespace
- [x] read_until_any
- [x] read_tag
- [x] read_whitespace
- [x] read_text
- [x] read_number
- [x] read_reference
- [x] read_select
- [x] read_optional
- [x] read_separated_by
- [x] read_lines
- [x] read_repeat
- [x] read_rule
- [x] read_node
