### ISSUE TITLE
Tracker issue: Release 1.0.1 with minor improvements to docs and codebase

### ISSUE THREAD

**Issue by bvssvni** [PistonDevelopers/meta#335]
- [x] Fixed typos (https://github.com/PistonDevelopers/meta/pull/331)
- [x] Use docs.rs for documentation link (https://github.com/PistonDevelopers/meta/pull/334, https://github.com/PistonDevelopers/meta/pull/336)
- [x] Add "Introduction" section to README (https://github.com/PistonDevelopers/meta/pull/338)

**Comment by bvssvni** [comment]
Closed by https://github.com/PistonDevelopers/meta/pull/339
